const arrayOfWordsMixed_6 = [
    "Phishing", "Scam",
    "Ransomware", "Attack",
    "Malware", "Infection",
    "Data", "Breach",
    "Spyware", "Threat", "Zero-Day",
    "Exploit", "Social", "Engineering",
    "Man", "in-the-Middle", "Denial",
    "of-Service", "Brute", "Force",
    "SQL", "Injection", "Cross-Site",
    "Scripting", "Credential",
    "Theft", "Botnet", "Operation",
    "Deep Packet", "Inspection",
    "Cryptojacking", "Scheme",
    "Spoofing", "Attack", "Drive-By",
    "Download"
];


const correctWordsJSON_6 = {
    "Phishing": "Scam",
    "Ransomware": "Attack",
    "Malware": "Infection",
    "Data": "Breach",
    "Spyware": "Threat",
    "Zero-Day": "Exploit",
    "Social": "Engineering",
    "Man": "in-the-Middle",
    "Denial": "of-Service",
    "Brute": "Force",
    "SQL": "Injection",
    "Cross-Site": "Scripting",
    "Credential": "Theft",
    "Botnet": "Operation",
    "Deep Packet": "Inspection",
    "Cryptojacking": "Scheme",
    "Spoofing": "Attack",
    "Drive-By": "Download"
};


const arrayOfWordsMixed_9 = [
    "Phishing", "Scam",
    "Ransomware", "Attack",
    "Malware", "Infection",
    "Data", "Breach",
    "Spyware", "Threat", "Zero-Day",
    "Exploit", "Social", "Engineering",
    "Man", "in-the-Middle", "Denial",
    "of-Service", "Brute", "Force",
    "SQL", "Injection", "Cross-Site",
    "Scripting", "Credential",
    "Theft", "Botnet", "Operation",
    "Deep Packet", "Inspection",
    "Cryptojacking", "Scheme",
    "Spoofing", "Attack", "Drive-By",
    "Download", "DNS", "Spoofing",
    "Keylogger", "Malware", "Bamboozle",
    "Gobbledygook", "Lollygag",
    "Flibbertigibbet", "Waddle",
    "Brouhaha", "Noodle",
    "Kerfuffle", "Malarkey",
    "Higgledy-piggledy",
    "Bumfuzzle", "Giggle",
    "Wobble", "Nincompoop",
    "Brouhaha", "Gadzooks",
    "Bibbles", "Dingbat",
    "Widdershins", "Snollygoster",
    "Lollygag", "Giggly",
    "Hobbledehoy", "Quibble",
    "Razzmatazz", "Skedaddle", "Bamboozle",
    "Snickersnee", "Fiddlesticks",
    "Gobsmacked", "Hodgepodge",
    "Higgledy-piggledy",
    "Lollygag", "Mumbo-jumbo",
    "Noodle", "Shenanigans",
    "Wiggly", "Whatchamacallit",
    "Ballyhoo", "Jibber-jabber", "Bruh!!!"
];


const correctWordsJSON = {
    "Phishing": "Scam",
    "Ransomware": "Attack",
    "Malware": "Infection",
    "Data": "Breach",
    "Spyware": "Threat",
    "Zero-Day": "Exploit",
    "Social": "Engineering",
    "Man": "in-the-Middle",
    "Denial": "of-Service",
    "Brute": "Force",
    "SQL": "Injection",
    "Cross-Site": "Scripting",
    "Credential": "Theft",
    "Botnet": "Operation",
    "Deep Packet": "Inspection",
    "Cryptojacking": "Scheme",
    "Spoofing": "Attack",
    "Drive-By": "Download",
    "DNS": "Spoofing",
    "Keylogger": "Malware"
};